# Generated by Django 6.0.4 on 2026-04-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_stripe", "0003_currency_item_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="value",
            field=models.CharField(default=""),
        ),
    ]
