# Generated by Django 6.0.4 on 2026-04-20 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_stripe", "0004_currency_value"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={"verbose_name_plural": "Currencies"},
        ),
        migrations.AlterField(
            model_name="currency",
            name="value",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="item",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="app_stripe.currency"
            ),
        ),
    ]
