# Generated by Django 6.0.4 on 2026-04-20 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_stripe", "0006_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="currency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="app_stripe.currency",
            ),
        ),
    ]
