# Generated by Django 6.0.4 on 2026-04-20 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_stripe", "0007_order_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="app_stripe.currency"
            ),
        ),
    ]
