# Generated by Django 6.0.4 on 2026-04-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_stripe", "0008_alter_order_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="currency",
        ),
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
