# Generated by Django 6.0.4 on 2026-04-20 11:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_stripe", "0010_discount_tax_order_discount_order_tax"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discount",
            name="code",
        ),
        migrations.RemoveField(
            model_name="tax",
            name="name",
        ),
    ]
