# Generated by Django 6.0.4 on 2026-04-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_stripe", "0011_remove_discount_code_remove_tax_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="percent",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
