# Generated by Django 6.0.4 on 2026-04-20 15:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_stripe", "0012_alter_discount_percent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tax",
            options={"verbose_name_plural": "Taxes"},
        ),
    ]
